import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Crow',
  description: 'AI-powered research and project management platform — works with Claude, ChatGPT, Gemini, Grok, Cursor, and more',
  base: '/software/crow/',

  srcExclude: ['superpowers/**'],

  head: [
    ['meta', { name: 'theme-color', content: '#1d1d1f' }],
    ['meta', { property: 'og:image', content: 'https://maestro.press/software/crow/crow-social-card.png' }],
    ['meta', { property: 'og:title', content: 'Crow — modular agentic framework + MCP platform' }],
    ['meta', { property: 'og:description', content: 'Self-host your own AI agents and apps. Connect Claude/ChatGPT/Cursor as a native MCP connector. Local or cloud models.' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
  ],

  locales: {
    root: {
      label: 'English',
      lang: 'en',
    },
    es: {
      label: 'Español',
      lang: 'es',
      themeConfig: {
        nav: [
          { text: 'Primeros Pasos', link: '/es/getting-started/' },
        ],
        sidebar: [
          {
            text: 'Primeros Pasos',
            items: [
              { text: 'Descripción General', link: '/es/getting-started/' },
              { text: 'Oracle Cloud Nivel Gratuito', link: '/es/getting-started/oracle-cloud' },
              { text: 'Google Cloud Nivel Gratuito', link: '/es/getting-started/google-cloud' },
              { text: 'Servidor en Casa', link: '/es/getting-started/home-server' },
              { text: 'Raspberry Pi (Crow OS)', link: '/es/getting-started/raspberry-pi' },
              { text: 'Instalación de Escritorio', link: '/es/getting-started/desktop-install' },
              { text: 'Windows (WSL2)', link: '/es/getting-started/windows-wsl2' },
              { text: 'Configuración de Escritorio', link: '/es/getting-started/desktop-setup' },
              { text: 'Docker', link: '/es/getting-started/docker' },
              { text: 'Instalación Completa', link: '/es/getting-started/full-setup' },
              { text: 'Hosting Gratuito', link: '/es/getting-started/free-hosting' },
              { text: 'Configuración de Tailscale', link: '/es/getting-started/tailscale-setup' },
              { text: 'Dominio Personalizado', link: '/es/getting-started/custom-domain' },
              { text: 'Multidispositivo', link: '/es/getting-started/multi-device' },
              { text: 'Despliegue en la Nube (Heredado)', link: '/es/getting-started/cloud-deploy' },
              { text: 'Opciones de IA Gratuita en la Nube', link: '/es/getting-started/free-cloud-ai' },
            ],
          },
          {
            text: 'Plataformas',
            items: [
              { text: 'Compatibilidad de Plataformas', link: '/es/platforms/' },
              { text: 'Claude Web y Móvil', link: '/es/platforms/claude' },
              { text: 'Claude Desktop', link: '/es/platforms/claude-desktop' },
              { text: 'Claude Code (CLI)', link: '/es/platforms/claude-code' },
              { text: 'ChatGPT', link: '/es/platforms/chatgpt' },
              { text: 'Gemini', link: '/es/platforms/gemini' },
              { text: 'Gemini CLI', link: '/es/platforms/gemini-cli' },
              { text: 'Grok (xAI)', link: '/es/platforms/grok' },
              { text: 'Cursor', link: '/es/platforms/cursor' },
              { text: 'Windsurf', link: '/es/platforms/windsurf' },
              { text: 'Cline', link: '/es/platforms/cline' },
              { text: 'Qwen Code', link: '/es/platforms/qwen-coder' },
              { text: 'Aplicación Android', link: '/es/platforms/android' },
              { text: 'iPhone (PWA)', link: '/es/platforms/ios' },
            ],
          },
          {
            text: 'Integraciones',
            items: [
              { text: 'Todas las Integraciones', link: '/es/integrations/' },
              { text: 'GitHub', link: '/es/integrations/github' },
              { text: 'Brave Search', link: '/es/integrations/brave-search' },
              { text: 'Slack', link: '/es/integrations/slack' },
              { text: 'Notion', link: '/es/integrations/notion' },
              { text: 'Trello', link: '/es/integrations/trello' },
              { text: 'Discord', link: '/es/integrations/discord' },
              { text: 'Google Workspace', link: '/es/integrations/google-workspace' },
              { text: 'Canvas LMS', link: '/es/integrations/canvas-lms' },
              { text: 'Microsoft Teams', link: '/es/integrations/microsoft-teams' },
              { text: 'Zotero', link: '/es/integrations/zotero' },
              { text: 'Home Assistant', link: '/es/integrations/home-assistant' },
              { text: 'Obsidian', link: '/es/integrations/obsidian' },
              { text: 'Render', link: '/es/integrations/render' },
              { text: 'Jellyfin', link: '/es/integrations/jellyfin' },
              { text: 'Plex', link: '/es/integrations/plex' },
              { text: 'IPTV', link: '/es/integrations/iptv' },
              { text: 'Kodi', link: '/es/integrations/kodi' },
              { text: 'Frigate', link: '/es/integrations/frigate' },
              { text: 'motionEye', link: '/es/integrations/motioneye' },
              { text: 'TriliumNext', link: '/es/integrations/trilium' },
              { text: 'Calibre Server', link: '/es/integrations/calibre-server' },
              { text: 'Calibre-Web', link: '/es/integrations/calibre-web' },
              { text: 'Miniflux', link: '/es/integrations/miniflux' },
              { text: 'Audiobookshelf', link: '/es/integrations/audiobookshelf' },
              { text: 'Kavita', link: '/es/integrations/kavita' },
              { text: 'Navidrome', link: '/es/integrations/navidrome' },
              { text: 'Paperless-ngx', link: '/es/integrations/paperless' },
              { text: 'Wallabag', link: '/es/integrations/wallabag' },
              { text: 'Linkding', link: '/es/integrations/linkding' },
              { text: 'Shiori', link: '/es/integrations/shiori' },
              { text: 'BookStack', link: '/es/integrations/bookstack' },
              { text: 'Vikunja', link: '/es/integrations/vikunja' },
              { text: 'Actual Budget', link: '/es/integrations/actual-budget' },
              { text: 'Funkwhale', link: '/es/integrations/funkwhale' },
            ],
          },
          {
            text: 'Arquitectura',
            items: [
              { text: 'Diseño del Sistema', link: '/es/architecture/' },
              { text: 'Servidor de Memoria', link: '/es/architecture/memory-server' },
              { text: 'Servidor de Proyectos', link: '/es/architecture/project-server' },
              { text: 'Servidor de Compartición', link: '/es/architecture/sharing-server' },
              { text: 'Protocolo de Relay', link: '/es/architecture/relay-protocol' },
              { text: 'Servidor de Almacenamiento', link: '/es/architecture/storage-server' },
              { text: 'Servidor de Blog', link: '/es/architecture/blog-server' },
              { text: 'Cancionero', link: '/es/architecture/songbook' },
              { text: "Crow's Nest", link: '/es/architecture/dashboard' },
              { text: 'Gateway', link: '/es/architecture/gateway' },
              { text: 'Crow OS', link: '/es/architecture/crow-os' },
              { text: 'Identidad Portátil', link: '/es/architecture/portable-identity' },
              { text: 'Gestión de Contexto', link: '/es/architecture/context-management' },
              { text: 'Sincronización Multi-Instancia', link: '/es/architecture/instances' },
              { text: 'Bot Builder', link: '/es/architecture/bot-builder' },
              { text: 'Compañero de IA', link: '/es/architecture/companion' },
              { text: 'Panel de Datos', link: '/es/architecture/data-dashboard' },
            ],
          },
          {
            text: 'Guías',
            items: [
              { text: 'Uso de Skills', link: '/es/guide/skills' },
              { text: 'Multiplataforma', link: '/es/guide/cross-platform' },
              { text: 'Panorama de Integraciones', link: '/es/guide/integration-overview' },
              { text: 'Almacenamiento', link: '/es/guide/storage' },
              { text: 'Blog', link: '/es/guide/blog' },
              { text: 'Podcast', link: '/es/guide/podcast' },
              { text: 'Cancionero', link: '/es/guide/songbook' },
              { text: 'Descubrimiento de Blogs', link: '/es/guide/blog-discovery' },
              { text: "Crow's Nest", link: '/es/guide/crows-nest' },
              { text: 'Pantalla de Inicio', link: '/es/guide/home-screen' },
              { text: 'Compartir', link: '/es/guide/sharing' },
              { text: 'Relays', link: '/es/guide/relays' },
              { text: 'Social y Mensajería', link: '/es/guide/social' },
              { text: 'Videollamadas y Audio', link: '/es/guide/calls' },
              { text: 'Notificaciones y Push', link: '/es/guide/notifications' },
              { text: 'Descubrimiento de Contactos', link: '/es/guide/contact-discovery' },
              { text: 'Bot Builder', link: '/es/guide/bot-builder' },
              { text: 'Tu Primer Bot (Tutorial)', link: '/es/guide/bot-builder-tutorial' },
              { text: 'Crow Messages', link: '/es/guide/crow-messages' },
              { text: 'Lentes Meta', link: '/es/guide/meta-glasses' },
              { text: 'Modo Kiosco', link: '/es/guide/kiosk-mode' },
              { text: 'Música', link: '/es/guide/music' },
              { text: 'Contexto y Rendimiento', link: '/es/guide/context-performance' },
              { text: 'Backends de Datos', link: '/es/guide/data-backends' },
              { text: 'Niveles de Despliegue', link: '/es/guide/deployment-tiers' },
              { text: 'Proveedores de IA (BYOAI)', link: '/es/guide/ai-providers' },
              { text: 'DashScope Coding Plan', link: '/es/guide/dashscope-coding' },
              { text: 'Z.AI Coding Plan', link: '/es/guide/zai-coding' },
              { text: 'Citas y Verificación', link: '/es/guide/citations' },
              { text: 'Ideación', link: '/es/guide/ideation' },
              { text: 'Personalización', link: '/es/guide/customization' },
              { text: 'Marca y Diseño', link: '/es/guide/brand' },
              { text: 'Programación', link: '/es/guide/scheduling' },
              { text: 'Extensiones', link: '/es/guide/extensions' },
              { text: 'Actualización Automática', link: '/es/guide/auto-update' },
              { text: 'Asistente de Declaración de Impuestos', link: '/es/guide/tax-filing' },
              { text: 'Automatización de Navegador', link: '/es/guide/browser-automation' },
              { text: 'Encadenamiento Multi-Instancia', link: '/es/guide/instances' },
              { text: 'Panel de Datos', link: '/es/guide/data-dashboard' },
              { text: 'Compartir Datos', link: '/es/guide/data-sharing' },
              { text: 'Contactos', link: '/es/guide/contacts' },
            ],
          },
          {
            text: 'Desarrolladores',
            items: [
              { text: 'Programa de Desarrolladores', link: '/es/developers/' },
              { text: 'Crear Complementos', link: '/es/developers/creating-addons' },
              { text: 'Registro de Complementos', link: '/es/developers/addon-registry' },
              { text: 'Tiendas Comunitarias', link: '/es/developers/community-stores' },
              { text: 'Capacidades de la Plataforma', link: '/es/developers/platform-capabilities' },
              { text: 'Crear Paneles', link: '/es/developers/creating-panels' },
              { text: 'Crear Servidores', link: '/es/developers/creating-servers' },
              { text: 'Construir Integraciones', link: '/es/developers/integrations' },
              { text: 'API de Almacenamiento', link: '/es/developers/storage-api' },
              { text: 'Referencia de Configuración', link: '/es/developers/configuration' },
              { text: 'Escribir Skills', link: '/es/developers/skills' },
              { text: 'Herramientas Centrales', link: '/es/developers/core-tools' },
              { text: 'Bundles Autoalojados', link: '/es/developers/bundles' },
              { text: 'Directorio Comunitario', link: '/es/developers/directory' },
              { text: 'Panel de Datos (Dev)', link: '/es/developers/data-dashboard' },
              { text: 'Nominatim GIS (Dev)', link: '/es/developers/nominatim' },
            ],
          },
        ],
      },
    },
  },

  themeConfig: {
    nav: [
      { text: 'Getting Started', link: '/getting-started/' },
      { text: 'Platforms', link: '/platforms/' },
      { text: 'Integrations', link: '/integrations/' },
      { text: 'Architecture', link: '/architecture/' },
      { text: 'Developers', link: '/developers/' },
    ],

    sidebar: [
      {
        text: 'Getting Started',
        items: [
          { text: 'Overview', link: '/getting-started/' },
          { text: 'Oracle Cloud Free Tier', link: '/getting-started/oracle-cloud' },
          { text: 'Google Cloud Free Tier', link: '/getting-started/google-cloud' },
          { text: 'Home Server', link: '/getting-started/home-server' },
          { text: 'Desktop Install', link: '/getting-started/desktop-install' },
          { text: 'Windows (WSL2)', link: '/getting-started/windows-wsl2' },
          { text: 'Tailscale Remote Access', link: '/getting-started/tailscale-setup' },
          { text: 'Custom Domain', link: '/getting-started/custom-domain' },
          { text: 'Docker', link: '/getting-started/docker' },
          { text: 'Free Hosting Comparison', link: '/getting-started/free-hosting' },
          { text: 'Cloud Deploy (Legacy)', link: '/getting-started/cloud-deploy' },
          { text: 'Cross-Platform Guide', link: '/guide/cross-platform' },
          { text: 'Desktop Setup (Claude Desktop)', link: '/getting-started/desktop-setup' },
          { text: 'Full Setup (MinIO + Gateway)', link: '/getting-started/full-setup' },
          { text: 'Raspberry Pi (Crow OS)', link: '/getting-started/raspberry-pi' },
          { text: 'Multi-Device Quick Start', link: '/getting-started/multi-device' },
          { text: 'Free Cloud AI Options', link: '/getting-started/free-cloud-ai' },
        ],
      },
      {
        text: 'Platforms',
        items: [
          { text: 'Compatibility', link: '/platforms/' },
          { text: 'Claude Web & Mobile', link: '/platforms/claude' },
          { text: 'Claude Desktop', link: '/platforms/claude-desktop' },
          { text: 'Claude Code (CLI)', link: '/platforms/claude-code' },
          { text: 'ChatGPT', link: '/platforms/chatgpt' },
          { text: 'Gemini', link: '/platforms/gemini' },
          { text: 'Gemini CLI', link: '/platforms/gemini-cli' },
          { text: 'Grok (xAI)', link: '/platforms/grok' },
          { text: 'Cursor', link: '/platforms/cursor' },
          { text: 'Windsurf', link: '/platforms/windsurf' },
          { text: 'Cline', link: '/platforms/cline' },
          { text: 'Qwen Code', link: '/platforms/qwen-coder' },

          { text: 'Android App', link: '/platforms/android' },
          { text: 'iPhone (PWA)', link: '/platforms/ios' },
        ],
      },
      {
        text: 'Integrations',
        items: [
          { text: 'All Integrations', link: '/integrations/' },
          { text: 'GitHub', link: '/integrations/github' },
          { text: 'Brave Search', link: '/integrations/brave-search' },
          { text: 'Slack', link: '/integrations/slack' },
          { text: 'Notion', link: '/integrations/notion' },
          { text: 'Trello', link: '/integrations/trello' },
          { text: 'Discord', link: '/integrations/discord' },
          { text: 'Google Workspace', link: '/integrations/google-workspace' },
          { text: 'Canvas LMS', link: '/integrations/canvas-lms' },
          { text: 'Microsoft Teams', link: '/integrations/microsoft-teams' },
          { text: 'Zotero', link: '/integrations/zotero' },
          { text: 'Home Assistant', link: '/integrations/home-assistant' },
          { text: 'Obsidian', link: '/integrations/obsidian' },
          { text: 'Render', link: '/integrations/render' },
          { text: 'Jellyfin', link: '/integrations/jellyfin' },
          { text: 'Plex', link: '/integrations/plex' },
          { text: 'IPTV', link: '/integrations/iptv' },
          { text: 'Kodi', link: '/integrations/kodi' },
          { text: 'Frigate', link: '/integrations/frigate' },
          { text: 'motionEye', link: '/integrations/motioneye' },
          { text: 'TriliumNext', link: '/integrations/trilium' },
          { text: 'Calibre Server', link: '/integrations/calibre-server' },
          { text: 'Calibre-Web', link: '/integrations/calibre-web' },
          { text: 'Miniflux', link: '/integrations/miniflux' },
          { text: 'Audiobookshelf', link: '/integrations/audiobookshelf' },
          { text: 'Kavita', link: '/integrations/kavita' },
          { text: 'Navidrome', link: '/integrations/navidrome' },
          { text: 'Paperless-ngx', link: '/integrations/paperless' },
          { text: 'Wallabag', link: '/integrations/wallabag' },
          { text: 'Linkding', link: '/integrations/linkding' },
          { text: 'Shiori', link: '/integrations/shiori' },
          { text: 'BookStack', link: '/integrations/bookstack' },
          { text: 'Vikunja', link: '/integrations/vikunja' },
          { text: 'Actual Budget', link: '/integrations/actual-budget' },
          { text: 'Funkwhale', link: '/integrations/funkwhale' },
        ],
      },
      {
        text: 'Architecture',
        items: [
          { text: 'System Design', link: '/architecture/' },
          { text: 'Memory Server', link: '/architecture/memory-server' },
          { text: 'Project Server', link: '/architecture/project-server' },
          { text: 'Sharing Server', link: '/architecture/sharing-server' },
          { text: 'Relay Protocol', link: '/architecture/relay-protocol' },
          { text: 'Storage Server', link: '/architecture/storage-server' },
          { text: 'Blog Server', link: '/architecture/blog-server' },
          { text: 'Songbook', link: '/architecture/songbook' },
          { text: "Crow's Nest", link: '/architecture/dashboard' },
          { text: 'Gateway', link: '/architecture/gateway' },
          { text: 'Crow OS', link: '/architecture/crow-os' },
          { text: 'Portable Identity', link: '/architecture/portable-identity' },
          { text: 'Context Management', link: '/architecture/context-management' },
          { text: 'Multi-Instance Sync', link: '/architecture/instances' },
          { text: 'Bot Builder', link: '/architecture/bot-builder' },
          { text: 'AI Companion', link: '/architecture/companion' },

          { text: 'Data Dashboard', link: '/architecture/data-dashboard' },
        ],
      },
      {
        text: 'Guides',
        items: [
          { text: 'Using Skills', link: '/guide/skills' },
          { text: 'Cross-Platform', link: '/guide/cross-platform' },
          { text: 'Integration Overview', link: '/guide/integration-overview' },
          { text: 'Storage', link: '/guide/storage' },
          { text: 'Blog', link: '/guide/blog' },
          { text: 'Podcast', link: '/guide/podcast' },
          { text: 'Songbook', link: '/guide/songbook' },
          { text: 'Blog Discovery', link: '/guide/blog-discovery' },
          { text: "Crow's Nest", link: '/guide/crows-nest' },
          { text: 'Home Screen', link: '/guide/home-screen' },
          { text: 'Sharing', link: '/guide/sharing' },
          { text: 'Relays', link: '/guide/relays' },
          { text: 'Social & Messaging', link: '/guide/social' },
          { text: 'Video & Audio Calls', link: '/guide/calls' },
          { text: 'Notifications & Push', link: '/guide/notifications' },
          { text: 'Contact Discovery', link: '/guide/contact-discovery' },
          { text: 'Bot Builder', link: '/guide/bot-builder' },
          { text: 'Your First Bot (Tutorial)', link: '/guide/bot-builder-tutorial' },
          { text: 'Crow Messages', link: '/guide/crow-messages' },
          { text: 'Meta Glasses', link: '/guide/meta-glasses' },
          { text: 'Kiosk Mode', link: '/guide/kiosk-mode' },
          { text: 'Music', link: '/guide/music' },
          { text: 'Context & Performance', link: '/guide/context-performance' },
          { text: 'Data Backends', link: '/guide/data-backends' },
          { text: 'Deployment Tiers', link: '/guide/deployment-tiers' },
          { text: 'AI Providers (BYOAI)', link: '/guide/ai-providers' },
          { text: 'DashScope Coding Plan', link: '/guide/dashscope-coding' },
          { text: 'Z.AI Coding Plan', link: '/guide/zai-coding' },
          { text: 'Citations & Verification', link: '/guide/citations' },
          { text: 'Ideation', link: '/guide/ideation' },
          { text: 'Customization', link: '/guide/customization' },
          { text: 'Brand & Design', link: '/guide/brand' },
          { text: 'Scheduling', link: '/guide/scheduling' },
          { text: 'Extensions', link: '/guide/extensions' },
          { text: 'Auto-Update', link: '/guide/auto-update' },
          { text: 'Tax Filing Assistant', link: '/guide/tax-filing' },
          { text: 'Browser Automation', link: '/guide/browser-automation' },
          { text: 'Multi-Instance Chaining', link: '/guide/instances' },
          { text: 'Data Dashboard', link: '/guide/data-dashboard' },
          { text: 'Data Sharing', link: '/guide/data-sharing' },
          { text: 'Contacts', link: '/guide/contacts' },
        ],
      },
      {
        text: 'Developers',
        items: [
          { text: 'Developer Program', link: '/developers/' },
          { text: 'Creating Add-ons', link: '/developers/creating-addons' },
          { text: 'Add-on Registry', link: '/developers/addon-registry' },
          { text: 'Community Stores', link: '/developers/community-stores' },
          { text: 'Platform Capabilities', link: '/developers/platform-capabilities' },
          { text: 'Creating Panels', link: '/developers/creating-panels' },
          { text: 'Creating Servers', link: '/developers/creating-servers' },
          { text: 'Building Integrations', link: '/developers/integrations' },
          { text: 'Storage API', link: '/developers/storage-api' },
          { text: 'Configuration Reference', link: '/developers/configuration' },
          { text: 'Writing Skills', link: '/developers/skills' },
          { text: 'Core Tools', link: '/developers/core-tools' },
          { text: 'Self-Hosted Bundles', link: '/developers/bundles' },
          { text: 'Community Directory', link: '/developers/directory' },
          { text: 'Data Dashboard Dev', link: '/developers/data-dashboard' },
          { text: 'Nominatim GIS Dev', link: '/developers/nominatim' },
        ],
      },
      {
        text: 'Skills',
        items: [
          { text: 'Overview', link: '/skills/' },
        ],
      },
      {
        text: 'Roadmap',
        items: [
          { text: 'Roadmap', link: '/roadmap' },
        ],
      },
      {
        text: 'Showcase',
        items: [
          { text: 'Showcase', link: '/showcase' },
        ],
      },
      {
        text: 'Legal',
        items: [
        ],
      },
      {
        text: 'Help',
        items: [
          { text: 'Troubleshooting', link: '/troubleshooting' },
        ],
      },
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/kh0pper/crow' },
    ],

    search: {
      provider: 'local',
    },

    footer: {
      message: 'Released under the MIT License.',
    },
  },
})
